id = "tinybird"
name = "Tinybird"
description = "Syntax highlighting for Tinybird files"
version = "0.0.1"
schema_version = 1
authors = ["Brad Love <brad@bradlove.co.za>"]
repository = "https://github.com/bradlove182/zed-tinybird"

[grammars.tinybird]
repository = "https://github.com/bradlove182/tree-sitter-tinybird"
rev = "main"
